language: php
php:
  - '7.3'

services:
  - postgresql

env:
  - APP_ENV=testing
  - DB_NAME=travis_ci_test
  - DB_USERNAME=postgres
  - DB_PORT=5432
  - DB_CONNECTION=pgsql

install:
  - composer self-update
  - make install

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - php artisan migrate --seed --no-interaction -vvv

script: make lint test
