language: php
php:
  - '7.3'

services:
  - postgresql

env:
  - APP_ENV=testing

install:
  - composer self-update
  - make install

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - php artisan migrate --no-interaction -vvv

script: make lint test
